### PR TITLE
Update 🍁2022-2023-Autumn-Term-OS-Seminar.md

### LINKED ISSUE #128: [Presentation] ASK-RoBERTa: A pretraining model for aspect-based sentiment classification via sentiment knowledge mining
### Title

ASK-RoBERTa: A pretraining model for aspect-based sentiment classification via sentiment knowledge mining

### Link

https://www.sciencedirect.com/science/article/abs/pii/S0950705122007584

### Year

2022

### Author and affiliation

Lan You a,b, Fanyu Han a,b, Jiaheng Peng a,b, Hong Jin a,b,* Christophe Claramunt c
a School of Computer Science and Information Engineering, Hubei University, Hubei Wuhan, 430062, China
b Engineering Research Center of Hubei Province in Intelligent Government Affairs and Application, of Artificial Intelligence, Hubei Wuhan, 430062, China
c Naval Academy Research Institute, Brest, 29240, France

### Conference or Journal

Knowledge-Based Systems

### Rank

SCIE

### Keywords

Aspect-based sentiment classification
RoBERTa
Sentiment knowledge
Dependency grammar
Knowledge mining

### Selecting Reason

情感分析任务可同样适用于Github的评论文本中。

### Supplementary

_No response_

### PR DESCRIPTION
**Pull request by PureNatural**
## Purpose

- Fix #128

## Changes

- Add agenda for 2022/10/24

### CODE REVIEW

**Comment by tyn1998** [comment]
Hi @PureNatural, apparently you followed the PR template and used a "Fix" keyword to link #128 to this PR, which is really welcomed by most communities if they provide a PR template in a GitHub repo. Using a keyword to link an issue is great if you want to that issue will be closed after the corresponding PR is merged.

But in this case, in my understanding, #128 is expected to remain `open` until your presentation is finished next Monday. So I think it would be better not use a keyword here.

Maybe we should improve the[ PR template](https://github.com/X-lab2017/open-research/blob/2f274b9270ad9036f8d89157a52d202f7a408787/.github/PULL_REQUEST_TEMPLATE.md) to give some guidance :)

**Comment by PureNatural** [comment]
> Hi @PureNatural, apparently you followed the PR template and used a "Fix" keyword to link #128 to this PR, which is really welcomed by most communities if they provide a PR template in a GitHub repo. Using a keyword to link an issue is great if you want to that issue will be closed after the corresponding PR is merged.
> 
> But in this case, in my understanding, #128 is expected to remain `open` until your presentation is finished next Monday. So I think it would be better not use a keyword here.
> 
> Maybe we should improve the[ PR template](https://github.com/X-lab2017/open-research/blob/2f274b9270ad9036f8d89157a52d202f7a408787/.github/PULL_REQUEST_TEMPLATE.md) to give some guidance :)

Thanks for your kind advice. I think you are right. 

I referred to this pr https://github.com/X-lab2017/open-research/pull/121. It used `Fix`, but the #114 is still open. There is a space between # and 114. It misled me. 

I will pay attention to the use of keywords when submitting the PR next time.

Much Thanks!

**Comment by birdflyi** [comment]
> Hi @PureNatural, apparently you followed the PR template and used a "Fix" keyword to link #128 to this PR, which is really welcomed by most communities if they provide a PR template in a GitHub repo. Using a keyword to link an issue is great if you want to that issue will be closed after the corresponding PR is merged.
> 
> But in this case, in my understanding, #128 is expected to remain `open` until your presentation is finished next Monday. So I think it would be better not use a keyword here.
> 
> Maybe we should improve the[ PR template](https://github.com/X-lab2017/open-research/blob/2f274b9270ad9036f8d89157a52d202f7a408787/.github/PULL_REQUEST_TEMPLATE.md) to give some guidance :)

we may reopen issue #71 to discuss about the [ PR template](https://github.com/X-lab2017/open-research/blob/2f274b9270ad9036f8d89157a52d202f7a408787/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by tyn1998** [comment]
> I referred to this pr #121. It used `Fix`, but the #114 is still open. There is a space between # and 114. It misled me.

Yeah, I had checked them and guessed you were misled by those PRs.

I'm really happy that I can help :)

**Pull request merged**
